name: Matthew James Flook
favicon: null
layout_spectrum: 0
typography_spectrum: 0.46598
title: Matthew James Flook
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.7013439643196762
  lightness: 0.302962094778195
  saturation: 0.8778529800474644
  rhythmicContrast: 0.9312918644864112
purpose: []
