name: Matthew James Flook
favicon: null
layout_spectrum: 0
typography_spectrum: 0.46598
title: Matthew James Flook
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#273419'
    - '#203310'
    - '#1d2d0e'
    - '#1b2a0c'
    - '#233115'
  brandStrength: 0.6875
  lightness: 0.6875
  saturation: 0
  rhythmicContrast: 1
purpose: []
