typography_spectrum: 0.14997599530033767
color:
  brandColors:
    - '#85DB18'
    - '#CDE855'
    - '#F5F6D4'
    - '#A7C520'
    - '#493F0B'
  brandStrength: 0.23618784826248884
  lightness: 0.329004475614056
  saturation: 0.8403367702849209
  rhythmicContrast: 0.2770247671287507
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.141557706752792
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: ''
  email: ''
  url: ''
name: Matthew James Flook
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About Me
    url: 'https://about.me/flook'
    type: external
  - name: Exit Signs
    url: 'http://exitsigns.io'
    type: external
  - name: Pinscape
    url: 'http://pinscape.com'
    type: external
  - name: Sevy-Verna
    url: 'http://sevyverna.com'
    type: external
  - name: Wake System
    url: 'http://wakesystem.net'
    type: external
favicon: null
title: ''
description: 'Always rushing, always late.'
purpose: []
