name: Matthew James Flook
favicon: null
layout_spectrum: 0.141557706752792
typography_spectrum: 0.3055618719663471
title: Matthew James Flook
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#85DB18'
    - '#CDE855'
    - '#F5F6D4'
    - '#A7C520'
    - '#493F0B'
  brandStrength: 0.23618784826248884
  lightness: 0.329004475614056
  saturation: 0.8403367702849209
  rhythmicContrast: 0.2770247671287507
purpose: []
