typography_spectrum: 0.33221263880841434
color:
  brandColors:
    - '#85DB18'
    - '#CDE855'
    - '#F5F6D4'
    - '#A7C520'
    - '#493F0B'
  brandStrength: 0.7887158333323896
  lightness: 0.560598224401474
  saturation: 0.7024918829556555
  rhythmicContrast: 0.9431150492746383
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8687396247405559
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: ''
  email: ''
  url: ''
name: Matthew James Flook
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About Me
    url: 'https://about.me/flook'
    type: external
  - name: Exit Signs
    url: 'http://exitsigns.io'
    type: external
  - name: Pinscape
    url: 'http://pinscape.com'
    type: external
  - name: Sevy-Verna
    url: 'http://sevyverna.com'
    type: external
  - name: Wake System
    url: 'http://wakesystem.net'
    type: external
favicon: null
title: 'Always rushing, always late.'
description: 'Always rushing, always late.'
purpose: []
