typography_spectrum: 0.4789641061797738
color:
  brandColors:
    - '#85DB18'
    - '#CDE855'
    - '#F5F6D4'
    - '#A7C520'
    - '#493F0B'
  brandStrength: 0.9551946106366813
  lightness: 0.0989496330730617
  saturation: 0.11472112592309713
  rhythmicContrast: 0.3490657026413828
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.4263126919977367
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: ''
  email: ''
  url: ''
name: Matthew James Flook
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About Me
    url: 'https://about.me/flook'
    type: external
  - name: Exit Signs
    url: 'http://exitsigns.io'
    type: external
  - name: Pinscape
    url: 'http://pinscape.com'
    type: external
  - name: Sevy-Verna
    url: 'http://sevyverna.com'
    type: external
  - name: Wake System
    url: 'http://wakesystem.net'
    type: external
favicon: null
title: Matthew James Flook
description: 'Always rushing, always late.'
purpose: []
